export const commandeActionTypes = {
    GET_COMMANDE_REQUEST: 'COMMANDE_GET_COMMANDE_REQUEST',
    GET_COMMANDE_SUCCESS: 'COMMANDE_GET_COMMANDE_SUCCESS',
    GET_COMMANDE_FAILURE: 'COMMANDE_GET_COMMANDE_FAILURE',
 
    ADD_PRODUIT: 'COMMANDE_ADD_PRODUIT',
    UPDATE_PRODUIT: 'COMMANDE_UPDATE_PRODUIT',
    DELETE_PRODUIT: 'COMMANDE_DELETE_PRODUIT',

    UPDATE_COMMANDE: 'COMMANDE_UPDATE_COMMANDE',
    DELETE_COMMANDE: 'COMMANDE_DELETE_COMMANDE',

    ADD_REGLEMENT: 'COMMANDE_ADD_REGLEMENT',
    REMOVE_REGLEMENT: 'COMMANDE_REMOVE_REGLEMENT',

    ADD_RENDU: 'COMMANDE_ADD_RENDU',
    REMOVE_RENDU: 'COMMANDE_REMOVE_RENDU',

    STANDBY_COMMANDE: 'COMMANDE_STANDBY_COMMANDE',
    REPRISE_COMMANDE: 'COMMANDE_REPRISE_COMMANDE',

    VALIDATE_COMMANDE_REQUEST: 'COMMANDE_VALIDATE_COMMANDE_REQUEST',
    VALIDATE_COMMANDE_SUCCESS: 'COMMANDE_VALIDATE_COMMANDE_SUCCESS',
    VALIDATE_COMMANDE_FAILURE: 'COMMANDE_VALIDATE_COMMANDE_FAILURE',

    GET_ALLCOMMANDES_REQUEST: 'COMMANDE_GET_ALLCOMMANDES_REQUEST',
    GET_ALLCOMMANDES_SUCCESS: 'COMMANDE_GET_ALLCOMMANDES_SUCCESS',
    GET_ALLCOMMANDES_FAILURE: 'COMMANDE_GET_ALLCOMMANDES_FAILURE',

};