export const commandeActionTypes = {
    GET_COMMANDE_REQUEST: 'COMMANDE_GET_COMMANDE_REQUEST',
    GET_COMMANDE_SUCCESS: 'COMMANDE_GET_COMMANDE_SUCCESS',
    GET_COMMANDE_FAILURE: 'COMMANDE_GET_COMMANDE_FAILURE',
 
    ADD_PRODUIT: 'COMMANDE_ADD_PRODUIT',
    UPDATE_PRODUIT: 'COMMANDE_UPDATE_PRODUIT',
    DELETE_PRODUIT: 'COMMANDE_DELETE_PRODUIT',

    UPDATE_COMMANDE: 'COMMANDE_UPDATE_COMMANDE',

    DELETE_CURRENT_COMMANDE: 'COMMANDE_DELETE_CURRENT_COMMANDE',
    
    DELETE_COMMANDE_REQUEST: 'COMMANDE_DELETE_COMMANDE_REQUEST',
    DELETE_COMMANDE_SUCCESS: 'COMMANDE_DELETE_COMMANDE_SUCCESS',
    DELETE_COMMANDE_FAILURE: 'COMMANDE_DELETE_COMMANDE_FAILURE',

    ADD_REGLEMENT: 'COMMANDE_ADD_REGLEMENT',
    REMOVE_REGLEMENT: 'COMMANDE_REMOVE_REGLEMENT',

    ADD_RENDU: 'COMMANDE_ADD_RENDU',
    REMOVE_RENDU: 'COMMANDE_REMOVE_RENDU',

    STANDBY_COMMANDE: 'COMMANDE_STANDBY_COMMANDE',
    AENCAISSER_COMMANDE: 'COMMANDE_AENCAISSER_COMMANDE',
    REPRISE_COMMANDE: 'COMMANDE_REPRISE_COMMANDE',

    VALIDATE_COMMANDE_REQUEST: 'COMMANDE_VALIDATE_COMMANDE_REQUEST',
    VALIDATE_COMMANDE_SUCCESS: 'COMMANDE_VALIDATE_COMMANDE_SUCCESS',
    VALIDATE_COMMANDE_FAILURE: 'COMMANDE_VALIDATE_COMMANDE_FAILURE',

    GET_ALLCOMMANDES_REQUEST: 'COMMANDE_GET_ALLCOMMANDES_REQUEST',
    GET_ALLCOMMANDES_SUCCESS: 'COMMANDE_GET_ALLCOMMANDES_SUCCESS',
    GET_ALLCOMMANDES_FAILURE: 'COMMANDE_GET_ALLCOMMANDES_FAILURE',

    ADD_INGREDIENT: 'COMMANDE_ADD_INGREDIENT',
    REMOVE_INGREDIENT: 'COMMANDE_REMOVE_INGREDIENT',
    STEP_NOINGREDIENT: 'COMMANDE_STEP_NOINGREDIENT',
    STEP_COMPLETE: 'COMMANDE_STEP_COMPLETE',
    STEP_UNCOMPLETE: 'COMMANDE_STEP_UNCOMPLETE',

    ARCHIVE_REQUEST: 'COMMANDE_ARCHIVE_REQUEST',
    ARCHIVE_SUCCESS: 'COMMANDE_ARCHIVE_SUCCESS',
    ARCHIVE_FAILURE: 'COMMANDE_ARCHIVE_FAILURE',

    ADD_COMMENT: 'COMMANDE_ADD_COMMENT',
    UPDATE_COMMENT: 'COMMANDE_UPDATE_COMMENT',
    DELETE_COMMENT: 'COMMANDE_DELETE_COMMENT',

    NEW_NUMERO: 'COMMANDE_NEW_NUMERO',
    SET_NEW_NUMERO: 'COMMANDE_SETNEW_NUMERO',
    NEW_NUMERO_ERROR: 'COMMANDE_NEW_NUMERO_ERROR',

    SET_COMMANDE_FROM_API: 'COMMANDE_SET_COMMANDE_FROM_API',

    GETALL_TICKETSRESTAU_REQUEST: 'COMMANDE_GETALL_TICKETSRESTAU_REQUEST',
    GETALL_TICKETSRESTAU_SUCCESS: 'COMMANDE_GETALL_TICKETSRESTAU_SUCCESS',
    GETALL_TICKETSRESTAU_FAILURE: 'COMMANDE_GETALL_TICKETSRESTAU_FAILURE',
    
    GET_TICKETRESTAU_REQUEST: 'COMMANDE_GET_TICKETRESTAU_REQUEST',
    GET_TICKETRESTAU_SUCCESS: 'COMMANDE_GET_TICKETRESTAU_SUCCESS',
    GET_TICKETRESTAU_FAILURE: 'COMMANDE_GET_TICKETRESTAU_FAILURE',
    
    PERSIST_TICKETRESTAU_REQUEST: 'COMMANDE_PERSIST_TICKETRESTAU_REQUEST',
    PERSIST_TICKETRESTAU_SUCCESS: 'COMMANDE_PERSIST_TICKETRESTAU_SUCCESS',
    PERSIST_TICKETRESTAU_FAILURE: 'COMMANDE_PERSIST_TICKETRESTAU_FAILURE'

};