export const commandeActionTypes = {
    GET_COMMANDE_REQUEST: 'COMMANDE_GET_COMMANDE_REQUEST',
    GET_COMMANDE_SUCCESS: 'COMMANDE_GET_COMMANDE_SUCCESS',
    GET_COMMANDE_FAILURE: 'COMMANDE_GET_COMMANDE_FAILURE',
 
    ADD_PRODUIT: 'COMMANDE_ADD_PRODUIT',
    UPDATE_PRODUIT: 'COMMANDE_UPDATE_PRODUIT',
    DELETE_PRODUIT: 'COMMANDE_DELETE_PRODUIT',

    UPDATE_COMMANDE: 'COMMANDE_UPDATE_COMMANDE',
    UPDATE_COMMANDE_ERROR: 'COMMANDE_UPDATE_COMMANDE_ERROR',

    DELETE_CURRENT_COMMANDE: 'COMMANDE_DELETE_CURRENT_COMMANDE',
    
    DELETE_COMMANDE_REQUEST: 'COMMANDE_DELETE_COMMANDE_REQUEST',
    DELETE_COMMANDE_SUCCESS: 'COMMANDE_DELETE_COMMANDE_SUCCESS',
    DELETE_COMMANDE_FAILURE: 'COMMANDE_DELETE_COMMANDE_FAILURE',

    ADD_REGLEMENT: 'COMMANDE_ADD_REGLEMENT',
    REMOVE_REGLEMENT: 'COMMANDE_REMOVE_REGLEMENT',

    ADD_RENDU: 'COMMANDE_ADD_RENDU',
    REMOVE_RENDU: 'COMMANDE_REMOVE_RENDU',
    
    ADD_TROP_PERCU: 'COMMANDE_ADD_TROP_PERCU',

    STANDBY_COMMANDE: 'COMMANDE_STANDBY_COMMANDE',
    AENCAISSER_COMMANDE: 'COMMANDE_AENCAISSER_COMMANDE',
    REPRISE_COMMANDE: 'COMMANDE_REPRISE_COMMANDE',

    VALIDATE_COMMANDE_REQUEST: 'COMMANDE_VALIDATE_COMMANDE_REQUEST',
    VALIDATE_COMMANDE_SUCCESS: 'COMMANDE_VALIDATE_COMMANDE_SUCCESS',
    VALIDATE_COMMANDE_FAILURE: 'COMMANDE_VALIDATE_COMMANDE_FAILURE',

    GET_ALLCOMMANDES_REQUEST: 'COMMANDE_GET_ALLCOMMANDES_REQUEST',
    GET_ALLCOMMANDES_SUCCESS: 'COMMANDE_GET_ALLCOMMANDES_SUCCESS',
    GET_ALLCOMMANDES_FAILURE: 'COMMANDE_GET_ALLCOMMANDES_FAILURE',

    GET_COMMANDESLIST_REQUEST: 'COMMANDE_GET_COMMANDESLIST_REQUEST',
    GET_COMMANDESLIST_SUCCESS: 'COMMANDE_GET_COMMANDESLIST_SUCCESS',
    GET_COMMANDESLIST_FAILURE: 'COMMANDE_GET_COMMANDESLIST_FAILURE',

    GET_COMMANDESNCLIST_REQUEST: 'COMMANDE_GET_COMMANDESNCLIST_REQUEST',
    GET_COMMANDESNCLIST_SUCCESS: 'COMMANDE_GET_COMMANDESNCLIST_SUCCESS',
    GET_COMMANDESNCLIST_FAILURE: 'COMMANDE_GET_COMMANDESNCLIST_FAILURE',

    ADD_INGREDIENT: 'COMMANDE_ADD_INGREDIENT',
    REMOVE_INGREDIENT: 'COMMANDE_REMOVE_INGREDIENT',
    STEP_NOINGREDIENT: 'COMMANDE_STEP_NOINGREDIENT',
    STEP_COMPLETE: 'COMMANDE_STEP_COMPLETE',
    STEP_UNCOMPLETE: 'COMMANDE_STEP_UNCOMPLETE',

    ARCHIVE_REQUEST: 'COMMANDE_ARCHIVE_REQUEST',
    ARCHIVE_SUCCESS: 'COMMANDE_ARCHIVE_SUCCESS',
    ARCHIVE_FAILURE: 'COMMANDE_ARCHIVE_FAILURE',

    SETSYNCED_REQUEST: 'COMMANDE_SETSYNCED_REQUEST',
    SETSYNCED_SUCCESS: 'COMMANDE_SETSYNCED_SUCCESS',
    SETSYNCED_FAILURE: 'COMMANDE_SETSYNCED_FAILURE',

    ADD_COMMENT: 'COMMANDE_ADD_COMMENT',
    UPDATE_COMMENT: 'COMMANDE_UPDATE_COMMENT',
    DELETE_COMMENT: 'COMMANDE_DELETE_COMMENT',

    ADD_DISCOUNT: 'COMMANDE_ADD_DISCOUNT',
    UPDATE_DISCOUNT: 'COMMANDE_UPDATE_DISCOUNT',
    DELETE_DISCOUNT: 'COMMANDE_DELETE_DISCOUNT',

    SET_COMMANDE_FROM_API: 'COMMANDE_SET_COMMANDE_FROM_API',

    GETALL_TICKETSRESTAU_REQUEST: 'COMMANDE_GETALL_TICKETSRESTAU_REQUEST',
    GETALL_TICKETSRESTAU_SUCCESS: 'COMMANDE_GETALL_TICKETSRESTAU_SUCCESS',
    GETALL_TICKETSRESTAU_FAILURE: 'COMMANDE_GETALL_TICKETSRESTAU_FAILURE',
    
    GET_TICKETRESTAU_REQUEST: 'COMMANDE_GET_TICKETRESTAU_REQUEST',
    GET_TICKETRESTAU_SUCCESS: 'COMMANDE_GET_TICKETRESTAU_SUCCESS',
    GET_TICKETRESTAU_FAILURE: 'COMMANDE_GET_TICKETRESTAU_FAILURE',
    
    PERSIST_TICKETRESTAU_REQUEST: 'COMMANDE_PERSIST_TICKETRESTAU_REQUEST',
    PERSIST_TICKETRESTAU_SUCCESS: 'COMMANDE_PERSIST_TICKETRESTAU_SUCCESS',
    PERSIST_TICKETRESTAU_FAILURE: 'COMMANDE_PERSIST_TICKETRESTAU_FAILURE',

    PERSIST_TICKETRESTAU_FROM_SYNC_REQUEST: 'COMMANDE_PERSIST_TICKETRESTAU_FROM_SYNC_REQUEST',
    PERSIST_TICKETRESTAU_FROM_SYNC_SUCCESS: 'COMMANDE_PERSIST_TICKETRESTAU_FROM_SYNC_SUCCESS',
    PERSIST_TICKETRESTAU_FROM_SYNC_FAILURE: 'COMMANDE_PERSIST_TICKETRESTAU_FROM_SYNC_FAILURE',
    
    DELETE_COMMANDE_FROM_SYNC_REQUEST: 'COMMANDE_DELETE_COMMANDE_FROM_SYNC_REQUEST',
    DELETE_COMMANDE_FROM_SYNC_SUCCESS: 'COMMANDE_DELETE_COMMANDE_FROM_SYNC_SUCCESS',
    DELETE_COMMANDE_FROM_SYNC_FAILURE: 'COMMANDE_DELETE_COMMANDE_FROM_SYNC_FAILURE',

    ARCHIVE_FROM_SYNC_REQUEST: 'COMMANDE_ARCHIVE_FROM_SYNC_REQUEST',
    ARCHIVE_FROM_SYNC_SUCCESS: 'COMMANDE_ARCHIVE_FROM_SYNC_SUCCESS',
    ARCHIVE_FROM_SYNC_FAILURE: 'COMMANDE_ARCHIVE_FROM_SYNC_FAILURE',

    SETSYNCED_FROM_SYNC_REQUEST: 'COMMANDE_SETSYNCED_FROM_SYNC_REQUEST',
    SETSYNCED_FROM_SYNC_SUCCESS: 'COMMANDE_SETSYNCED_FROM_SYNC_SUCCESS',
    SETSYNCED_FROM_SYNC_FAILURE: 'COMMANDE_SETSYNCED_FROM_SYNC_FAILURE',

    SET_COMMANDE_FROM_SYNC_SUCCESS: 'COMMANDE_SET_COMMANDE_FROM_SYNC_SUCCESS',
    SET_COMMANDE_FROM_SYNC_FAILURE: 'COMMANDE_SET_COMMANDE_FROM_SYNC_FAILURE',

    GET_COMMANDES_CAISSES_REQUEST: 'COMMANDE_GET_COMMANDES_CAISSES_REQUEST',
    GET_COMMANDES_CAISSES_SUCCESS: 'COMMANDE_GET_COMMANDES_CAISSES_SUCCESS',
    GET_COMMANDES_CAISSES_FAILURE: 'COMMANDE_GET_COMMANDES_CAISSES_FAILURE',

    CHECK_DISCOUNT: 'COMMANDE_CHECK_DISCOUNT',

    SET_SCHEDULE: 'COMMANDE_SET_SCHEDULE',
    DELETE_SCHEDULE: 'COMMANDE_DELETE_SCHEDULE',

    GET_LOTS: 'COMMANDE_GET_LOTS',
    CREATE_LOT: 'COMMANDE_CREATE_LOT',
    DELETE_LOT: 'DELETE_CREATE_LOT',
    ADD_COMMANDE_TO_LOT: 'COMMANDE_ADD_COMMANDE_TO_LOT',
    PAST_NONCONFIRMEDCMD: 'COMMANDE_PAST_NONCONFIRMEDCMD',

};