export const clientsActionTypes = {

  GETALL_REQUEST: 'CLIENTS_GETALL_REQUEST',
  GETALL_SUCCESS: 'CLIENTS_GETALL_SUCCESS',
  GETALL_FAILURE: 'CLIENTS_GETALL_FAILURE',

  CREATE_REQUEST: 'CLIENTS_ADD_REQUEST',
  CREATE_SUCCESS: 'CLIENTS_ADD_SUCCESS',
  CREATE_FAILURE: 'CLIENTS_ADD_FAILURE',

  UPDATE_REQUEST: 'CLIENTS_UPDATE_REQUEST',
  UPDATE_SUCCESS: 'CLIENTS_UPDATE_SUCCESS',
  UPDATE_FAILURE: 'CLIENTS_UPDATE_FAILURE',

  FIND_CLIENT: 'CLIENTS_FIND_CLIENT'

}