export const tresorActionTypes = {

  ADD_REQUEST: 'TRESORERIE_ADD_REQUEST',
  ADD_SUCCESS: 'TRESORERIE_ADD_SUCCESS',
  ADD_FAILURE: 'TRESORERIE_ADD_FAILURE',

  GET_REQUEST: 'TRESORERIE_GET_REQUEST',
  GET_SUCCESS: 'TRESORERIE_GET_SUCCESS',
  GET_FAILURE: 'TRESORERIE_GET_FAILURE',

  GET_LASTCLOTUREANDAFTER_REQUEST: 'TRESORERIE_GETLASTCLOTUREANDAFTER_REQUEST',
  GET_LASTCLOTUREANDAFTER_SUCCESS: 'TRESORERIE_GETLASTCLOTUREANDAFTER_SUCCESS',
  GET_LASTCLOTUREANDAFTER_FAILURE: 'TRESORERIE_GETLASTCLOTUREANDAFTER_FAILURE',

  GET_LASTOUVERTUREANDAFTER_REQUEST: 'TRESORERIE_GETLASTOUVERTUREANDAFTER_REQUEST',
  GET_LASTOUVERTUREANDAFTER_SUCCESS: 'TRESORERIE_GETLASTOUVERTUREANDAFTER_SUCCESS',
  GET_LASTOUVERTUREANDAFTER_FAILURE: 'TRESORERIE_GETLASTOUVERTUREANDAFTER_FAILURE',
  
  UPDATE_REQUEST: 'TRESORERIE_UPDATE_REQUEST',
  UPDATE_SUCCESS: 'TRESORERIE_UPDATE_SUCCESS',
  UPDATE_FAILURE: 'TRESORERIE_UPDATE_FAILURE',

  SETSYNCED_REQUEST: 'TRESORERIE_SETSYNCED_REQUEST',
  SETSYNCED_SUCCESS: 'TRESORERIE_SETSYNCED_SUCCESS',
  SETSYNCED_FAILURE: 'TRESORERIE_SETSYNCED_FAILURE',
  
}