export const tresorActionTypes = {

  ADD_REQUEST: 'TRESORERIE_ADD_REQUEST',
  ADD_SUCCESS: 'TRESORERIE_ADD_SUCCESS',
  ADD_FAILURE: 'TRESORERIE_ADD_FAILURE',

  GET_REQUEST: 'TRESORERIE_GET_REQUEST',
  GET_SUCCESS: 'TRESORERIE_GET_SUCCESS',
  GET_FAILURE: 'TRESORERIE_GET_FAILURE',
  
  UPDATE_REQUEST: 'TRESORERIE_UPDATE_REQUEST',
  UPDATE_SUCCESS: 'TRESORERIE_UPDATE_SUCCESS',
  UPDATE_FAILURE: 'TRESORERIE_UPDATE_FAILURE',

  SETSYNCED_REQUEST: 'TRESORERIE_SETSYNCED_REQUEST',
  SETSYNCED_SUCCESS: 'TRESORERIE_SETSYNCED_SUCCESS',
  SETSYNCED_FAILURE: 'TRESORERIE_SETSYNCED_FAILURE',
  
}