export const userActionTypes = {

  CREATE_REQUEST: 'USER_CREATE_REQUEST',
  CREATE_SUCCESS: 'USER_CREATE_SUCCESS',
  CREATE_FAILURE: 'USER_CREATE_FAILURE',

  LOGIN_REQUEST: 'USER_LOGIN_REQUEST',
  LOGIN_SUCCESS: 'USER_LOGIN_SUCCESS',
  LOGIN_FAILURE: 'USER_LOGIN_FAILURE',
  LOGIN_ERROR: 'USER_LOGIN_ERROR',
  LOGIN_DENIED: 'USER_LOGIN_DENIED',
  RESET_LOGIN_ERROR: 'USER_RESET_LOGIN_ERROR',

  AUTHENT_REQUEST: 'USER_AUTHENT_REQUEST',
  AUTHENT_SUCCESS: 'USER_AUTHENT_SUCCESS',
  AUTHENT_FAILURE: 'USER_AUTHENT_FAILURE',

  CHECK_REQUEST: 'USER_CHECK_REQUEST',
  CHECK_SUCCESS: 'USER_CHECK_SUCCESS',
  CHECK_FAILURE: 'USER_CHECK_FAILURE',

  UPDATE_REQUEST: 'USER_UPDATE_REQUEST',
  UPDATE_SUCCESS: 'USER_UPDATE_SUCCESS',
  UPDATE_FAILURE: 'USER_UPDATE_FAILURE',

  SET_ADMIN_REQUEST: 'USER_SET_ADMIN_REQUEST',
  SET_ADMIN_SUCCESS: 'USER_SET_ADMIN_SUCCESS',
  SET_ADMIN_FAILURE: 'USER_SET_ADMIN_FAILURE',

  LOGOUT: 'USER_LOGOUT',

  GETALL_REQUEST: 'USER_GETALL_REQUEST',
  GETALL_SUCCESS: 'USER_GETALL_SUCCESS',
  GETALL_FAILURE: 'USER_GETALL_FAILURE',

  DELETE_REQUEST: 'USER_DELETE_REQUEST',
  DELETE_SUCCESS: 'USER_DELETE_SUCCESS',
  DELETE_FAILURE: 'USER_DELETE_FAILURE'

};