export const marketingActionTypes = {

  GET_AVOIRS_LIST_REQUEST: 'MARKETING_GET_AVOIRS_LIST_REQUEST',
  GET_AVOIRS_LIST_SUCCESS: 'MARKETING_GET_AVOIRS_LIST_SUCCESS',
  GET_AVOIRS_LIST_FAILURE: 'MARKETING_GET_AVOIRS_LIST_FAILURE',

  CREATE_AVOIR_REQUEST: 'MARKETING_CREATE_AVOIR_REQUEST',
  CREATE_AVOIR_SUCCESS: 'MARKETING_CREATE_AVOIR_SUCCESS',
  CREATE_AVOIR_FAILURE: 'MARKETING_CREATE_AVOIR_FAILURE',

  UPDATE_AVOIR_REQUEST: 'MARKETING_UPDATE_AVOIR_REQUEST',
  UPDATE_AVOIR_SUCCESS: 'MARKETING_UPDATE_AVOIR_SUCCESS',
  UPDATE_AVOIR_FAILURE: 'MARKETING_UPDATE_AVOIR_FAILURE',

  DELETE_AVOIR_REQUEST: 'MARKETING_DELETE_AVOIR_REQUEST',
  DELETE_AVOIR_SUCCESS: 'MARKETING_DELETE_AVOIR_SUCCESS',
  DELETE_AVOIR_FAILURE: 'MARKETING_DELETE_AVOIR_FAILURE',

  GET_REGLESPANIER_LIST_REQUEST: 'MARKETING_GET_REGLESPANIER_LIST_REQUEST',
  GET_REGLESPANIER_LIST_SUCCESS: 'MARKETING_GET_REGLESPANIER_LIST_SUCCESS',
  GET_REGLESPANIER_LIST_FAILURE: 'MARKETING_GET_REGLESPANIER_LIST_FAILURE',

  CREATE_REGLEPANIER_REQUEST: 'MARKETING_CREATE_REGLEPANIER_REQUEST',
  CREATE_REGLEPANIER_SUCCESS: 'MARKETING_CREATE_REGLEPANIER_SUCCESS',
  CREATE_REGLEPANIER_FAILURE: 'MARKETING_CREATE_REGLEPANIER_FAILURE',

  UPDATE_REGLEPANIER_REQUEST: 'MARKETING_UPDATE_REGLEPANIER_REQUEST',
  UPDATE_REGLEPANIER_SUCCESS: 'MARKETING_UPDATE_REGLEPANIER_SUCCESS',
  UPDATE_REGLEPANIER_FAILURE: 'MARKETING_UPDATE_REGLEPANIER_FAILURE',

  DELETE_REGLEPANIER_REQUEST: 'MARKETING_DELETE_REGLEPANIER_REQUEST',
  DELETE_REGLEPANIER_SUCCESS: 'MARKETING_DELETE_REGLEPANIER_SUCCESS',
  DELETE_REGLEPANIER_FAILURE: 'MARKETING_DELETE_REGLEPANIER_FAILURE',


  GET_REGLESCATALOGUE_LIST_REQUEST: 'MARKETING_GET_REGLESCATALOGUE_LIST_REQUEST',
  GET_REGLESCATALOGUE_LIST_SUCCESS: 'MARKETING_GET_REGLESCATALOGUE_LIST_SUCCESS',
  GET_REGLESCATALOGUE_LIST_FAILURE: 'MARKETING_GET_REGLESCATALOGUE_LIST_FAILURE',

  CREATE_REGLECATALOGUE_REQUEST: 'MARKETING_CREATE_REGLECATALOGUE_REQUEST',
  CREATE_REGLECATALOGUE_SUCCESS: 'MARKETING_CREATE_REGLECATALOGUE_SUCCESS',
  CREATE_REGLECATALOGUE_FAILURE: 'MARKETING_CREATE_REGLECATALOGUE_FAILURE',

  UPDATE_REGLECATALOGUE_REQUEST: 'MARKETING_UPDATE_REGLECATALOGUE_REQUEST',
  UPDATE_REGLECATALOGUE_SUCCESS: 'MARKETING_UPDATE_REGLECATALOGUE_SUCCESS',
  UPDATE_REGLECATALOGUE_FAILURE: 'MARKETING_UPDATE_REGLECATALOGUE_FAILURE',

  DELETE_REGLECATALOGUE_REQUEST: 'MARKETING_DELETE_REGLECATALOGUE_REQUEST',
  DELETE_REGLECATALOGUE_SUCCESS: 'MARKETING_DELETE_REGLECATALOGUE_SUCCESS',
  DELETE_REGLECATALOGUE_FAILURE: 'MARKETING_DELETE_REGLECATALOGUE_FAILURE',

  SET_AVOIR_FROM_SYNC: 'MARKETING_SET_AVOIR_FROM_SYNC',
  DELETE_AVOIR_FROM_SYNC: 'MARKETING_DELETE_AVOIR_FROM_SYNC',

  GET_GIFT_REQUEST: 'MARKETING_GET_GIFT_REQUEST',
  GET_GIFT_SUCCESS: 'MARKETING_GET_GIFT_SUCCESS',
  GET_GIFT_FAILURE: 'MARKETING_GET_GIFT_FAILURE',

  GET_GIFTS_LIST_REQUEST: 'MARKETING_GET_GIFTS_LIST_REQUEST',
  GET_GIFTS_LIST_SUCCESS: 'MARKETING_GET_GIFTS_LIST_SUCCESS',
  GET_GIFTS_LIST_FAILURE: 'MARKETING_GET_GIFTS_LIST_FAILURE',

  BURN_GIFT_REQUEST: 'MARKETING_BURN_GIFT_REQUEST',
  BURN_GIFT_SUCCESS: 'MARKETING_BURN_GIFT_SUCCESS',
  BURN_GIFT_FAILURE: 'MARKETING_BURN_GIFT_FAILURE',
};