export const catalogueActionTypes = {

  GETALL_ACTIVE_REQUEST: 'CATALOGUE_GETALL_ACTIVE_REQUEST',
  GETALL_ACTIVE_SUCCESS: 'CATALOGUE_GETALL_ACTIVE_SUCCESS',
  GETALL_ACTIVE_FAILURE: 'CATALOGUE_GETALL_ACTIVE_FAILURE',

  GETALL_REQUEST: 'CATALOGUE_GETALL_REQUEST',
  GETALL_SUCCESS: 'CATALOGUE_GETALL_SUCCESS',
  GETALL_FAILURE: 'CATALOGUE_GETALL_FAILURE',
};