export const evenements = {
  "10": {code: 10, intitule: " Changement du mode de gestion de la séquence continue", purgeable: false},
  "20": {code: 20, intitule: "Archivage fiscal de période", purgeable: true},
  "30": {code: 30, intitule: "Archivage fiscal d'année ou d'exercice", purgeable: false},
  "40": {code: 40, intitule: "Arrêt du terminal, déconnexion, fermeture de session", purgeable: true},
  "50": {code: 50, intitule: "Clôture de période", purgeable: true},
  "60": {code: 60, intitule: "Clôture annuelle ou d’exercice", purgeable: false},
  "70": {code: 70, intitule: "Début de mode dégradé", purgeable: false},
  "80": {code: 80, intitule: "Démarrage du terminal, connexion, ouverture de session", purgeable: true},
  "90": {code: 90, intitule: "Détection d’un défaut d’intégrité dans les données sécurisées ou dans une archive fiscale", purgeable: false},
  "95": {code: 95, intitule: "Détection d'une rupture de la séquence continue", purgeable: false},
  "100": {code:100, intitule: "Début de l'exécution d'une fonction spéciale", purgeable: false},
  "105": {code:105, intitule: "Fin de l'exécution d'une fonction spéciale", purgeable: false},
  "110": {code:110, intitule: "Exportation de données", purgeable: true},
  "120": {code:120, intitule: "Fin de mode dégradé", purgeable: false},
  "123": {code:123, intitule: "Renvoi forcé de données vers le système central", purgeable: false},
  "125": {code:125, intitule: "Centralisation des données après la fin du mode dégradé", purgeable: false},
  "126": {code:126, intitule: "Rajout d’un point de vente ou d’un poste utilisateur", purgeable: false},
  "127": {code:127, intitule: "Suppression d’un point de vente ou d’un poste utilisateur", purgeable: false},
  "128": {code:128, intitule: "Changement d'assujetti utilisant le système d'encaissement", purgeable: false},
  "130": {code:130, intitule: "Habilitation d’utilisateur/Gestion des droits", purgeable: true},
  "140": {code:140, intitule: "Importation de données externes", purgeable: true},
  "150": {code:150, intitule: "Imprimante indisponible", purgeable: true},
  "155": {code:155, intitule: "Duplicata d’une note", purgeable: true},
  "156": {code:156, intitule: "Duplicata d’un justificatif de paiement", purgeable: true},
  "160": {code:160, intitule: "Enregistrement des écritures en comptabilité", purgeable: false},
  "170": {code:170, intitule: "Traitement de fond de caisse", purgeable: true},
  "180": {code:180, intitule: "Génération d'un fichier d'exportation des écritures comptables", purgeable: true},
  "190": {code:190, intitule: "Annulation de pièce justificative ticket", purgeable: true},
  "200": {code:200, intitule: "Purge des données", purgeable: false},
  "205": {code:205, intitule: "Purge Partielle du JET", purgeable: false},
  "210": {code:210, intitule: "Reprise de données d’autres logiciels suite à changement de systèmes", purgeable: false},
  "220": {code:220, intitule: "Restauration d’une base de données", purgeable: false},
  "230": {code:230, intitule: "Sauvegarde d’une base de données", purgeable: false},
  "240": {code:240, intitule: "Suivi des interventions de maintenance", purgeable: false},
  "250": {code:250, intitule: "Installation d’une nouvelle version majeure du logiciel", purgeable: false},
  "255": {code:255, intitule: "Installation d’une nouvelle version mineure du logiciel", purgeable: true},
  "260": {code:260, intitule: "Initialisation des données", purgeable: false},
  "270": {code:270, intitule: "Evolution de paramètre de conformité aux règles", purgeable: false},
  "280": {code:280, intitule: "Début/fin d’opération de contrôle fiscal", purgeable: true},
  "290": {code:290, intitule: "Echange avec un expert-comptable", purgeable: true},
  "295": {code:295, intitule: "Transfert de fichier à la demande de l'administration", purgeable: false},
  "300": {code:300, intitule: "Activation de paramètre autorisé et documenté", purgeable: false},
  "320": {code:320, intitule: "Abandon d’une opération de vente (transaction) commerciale non encore enregistrée", purgeable: true},
  "323": {code:323, intitule: "Annulation d’une ligne d’article", purgeable: true},
  "324": {code:324, intitule: "Abandon d'une note validée", purgeable: true},
  "325": {code:325, intitule: "Annulation(s) d’article(s) après commande", purgeable: true},
  "326": {code:326, intitule: "Retour(s) d'article(s) après une émission d’une note", purgeable: true},
  "327": {code:327, intitule: "Passage en note « offerte »", purgeable: true},
  "328": {code:328, intitule: "Passage d’article en « offert »", purgeable: true},
  "329": {code:329, intitule: "Non édition d’une note", purgeable: true},
  "330": {code:330, intitule: "Initialisation de la clôture de fin de période", purgeable: true},
  "400": {code:400, intitule: "Changement de la durée de l’exercice", purgeable: false},
  "410": {code:410, intitule: "Changement de données affectant l’identification de l’assujetti ou du mandataire", purgeable: false},
  "420": {code:420, intitule: "Changement du mode de règlement, après émission du ticket", purgeable: true},
  "430": {code:430, intitule: "Changement de table affectée à une note", purgeable: true},
  "440": {code:440, intitule: "Transfert des archives fiscales sur support externe", purgeable: false},
  "450": {code:450, intitule: "Traçabilité du changement du trousseau de clés utilisé pour signer", purgeable: false},
  "901": {code:901, intitule: "Ouverture du tiroir-caisse", purgeable: true},
  "902": {code:902, intitule: "Signature de l’export comptable", purgeable: true}
};