export const catalogueActionTypes = {

  GETALL_ACTIVE_REQUEST: 'CATALOGUE_GETALL_ACTIVE_REQUEST',
  GETALL_ACTIVE_SUCCESS: 'CATALOGUE_GETALL_ACTIVE_SUCCESS',
  GETALL_ACTIVE_FAILURE: 'CATALOGUE_GETALL_ACTIVE_FAILURE',

  GETALL_REQUEST: 'CATALOGUE_GETALL_REQUEST',
  GETALL_SUCCESS: 'CATALOGUE_GETALL_SUCCESS',
  GETALL_FAILURE: 'CATALOGUE_GETALL_FAILURE',

  UPDATE_PRODUIT_REQUEST: 'CATALOGUE_UPDATE_PRODUIT_REQUEST',
  UPDATE_PRODUIT_SUCCESS: 'CATALOGUE_UPDATE_PRODUIT_SUCCESS',
  UPDATE_PRODUIT_FAILURE: 'CATALOGUE_UPDATE_PRODUIT_FAILURE',
  UPDATE_PRODUIT_FROM_SYNC: 'CATALOGUE_UPDATE_PRODUIT_FROM_SYNC',

  UPDATE_INGREDIENT_REQUEST: 'CATALOGUE_UPDATE_INGREDIENT_REQUEST',
  UPDATE_INGREDIENT_SUCCESS: 'CATALOGUE_UPDATE_INGREDIENT_SUCCESS',
  UPDATE_INGREDIENT_FAILURE: 'CATALOGUE_UPDATE_INGREDIENT_FAILURE',
  UPDATE_INGREDIENT_FROM_SYNC: 'CATALOGUE_UPDATE_INGREDIENT_FROM_SYNC',

  UPDATE_GROUPE_REQUEST: 'CATALOGUE_UPDATE_GROUPE_REQUEST',
  UPDATE_GROUPE_SUCCESS: 'CATALOGUE_UPDATE_GROUPE_SUCCESS',
  UPDATE_GROUPE_FAILURE: 'CATALOGUE_UPDATE_GROUPE_FAILURE',
  UPDATE_GROUPE_FROM_SYNC: 'CATALOGUE_UPDATE_GROUPE_FROM_SYNC',

  UPDATE_TYPE_REQUEST: 'CATALOGUE_UPDATE_TYPE_REQUEST',
  UPDATE_TYPE_SUCCESS: 'CATALOGUE_UPDATE_TYPE_SUCCESS',
  UPDATE_TYPE_FAILURE: 'CATALOGUE_UPDATE_TYPE_FAILURE',
  UPDATE_TYPE_FROM_SYNC: 'CATALOGUE_UPDATE_TYPE_FROM_SYNC'
};