export const employesActionTypes = {

  CLOCKIN_REQUEST: 'EMPLOYES_CLOCKIN_REQUEST',
  CLOCKIN_SUCCESS: 'EMPLOYES_CLOCKIN_SUCCESS',
  CLOCKIN_FAILURE: 'EMPLOYES_CLOCKIN_FAILURE',

  CLOCKOUT_REQUEST: 'EMPLOYES_CLOCKOUT_REQUEST',
  CLOCKOUT_SUCCESS: 'EMPLOYES_CLOCKOUT_SUCCESS',
  CLOCKOUT_FAILURE: 'EMPLOYES_CLOCKOUT_FAILURE',

  GET_POINTAGES_LIST_REQUEST: 'EMPLOYES_GET_POINTAGES_LIST_REQUEST',
  GET_POINTAGES_LIST_SUCCESS: 'EMPLOYES_GET_POINTAGES_LIST_SUCCESS',
  GET_POINTAGES_LIST_FAILURE: 'EMPLOYES_GET_POINTAGES_LIST_FAILURE'
};