export const employesActionTypes = {

  CLOCKIN_REQUEST: 'EMPLOYES_CLOCKIN_REQUEST',
  CLOCKIN_SUCCESS: 'EMPLOYES_CLOCKIN_SUCCESS',
  CLOCKIN_FAILURE: 'EMPLOYES_CLOCKIN_FAILURE',

  CLOCKOUT_REQUEST: 'EMPLOYES_CLOCKOUT_REQUEST',
  CLOCKOUT_SUCCESS: 'EMPLOYES_CLOCKOUT_SUCCESS',
  CLOCKOUT_FAILURE: 'EMPLOYES_CLOCKOUT_FAILURE',

  SET_POINTAGE_FROM_SYNC: 'EMPLOYES_SET_POINTAGE_FROM_SYNC',

  GET_POINTAGES_LIST_REQUEST: 'EMPLOYES_GET_POINTAGES_LIST_REQUEST',
  GET_POINTAGES_LIST_SUCCESS: 'EMPLOYES_GET_POINTAGES_LIST_SUCCESS',
  GET_POINTAGES_LIST_FAILURE: 'EMPLOYES_GET_POINTAGES_LIST_FAILURE',

  GET_SHIFTS_LIST_REQUEST: 'EMPLOYES_GET_SHIFTS_LIST_REQUEST',
  GET_SHIFTS_LIST_SUCCESS: 'EMPLOYES_GET_SHIFTS_LIST_SUCCESS',
  GET_SHIFTS_LIST_FAILURE: 'EMPLOYES_GET_SHIFTS_LIST_FAILURE',

  CREATE_SHIFT_REQUEST: 'EMPLOYES_CREATE_SHIFT_REQUEST',
  CREATE_SHIFT_SUCCESS: 'EMPLOYES_CREATE_SHIFT_SUCCESS',
  CREATE_SHIFT_FAILURE: 'EMPLOYES_CREATE_SHIFT_FAILURE',

  UPDATE_SHIFT_REQUEST: 'EMPLOYES_UPDATE_SHIFT_REQUEST',
  UPDATE_SHIFT_SUCCESS: 'EMPLOYES_UPDATE_SHIFT_SUCCESS',
  UPDATE_SHIFT_FAILURE: 'EMPLOYES_UPDATE_SHIFT_FAILURE',

  DELETE_SHIFT_REQUEST: 'EMPLOYES_DELETE_SHIFT_REQUEST',
  DELETE_SHIFT_SUCCESS: 'EMPLOYES_DELETE_SHIFT_SUCCESS',
  DELETE_SHIFT_FAILURE: 'EMPLOYES_DELETE_SHIFT_FAILURE',

  GET_TIMEADJUSTS_LIST_REQUEST: 'EMPLOYES_GET_TIMEADJUSTS_LIST_REQUEST',
  GET_TIMEADJUSTS_LIST_SUCCESS: 'EMPLOYES_GET_TIMEADJUSTS_LIST_SUCCESS',
  GET_TIMEADJUSTS_LIST_FAILURE: 'EMPLOYES_GET_TIMEADJUSTS_LIST_FAILURE',

  CREATE_TIMEADJUST_REQUEST: 'EMPLOYES_CREATE_TIMEADJUST_REQUEST',
  CREATE_TIMEADJUST_SUCCESS: 'EMPLOYES_CREATE_TIMEADJUST_SUCCESS',
  CREATE_TIMEADJUST_FAILURE: 'EMPLOYES_CREATE_TIMEADJUST_FAILURE',

  UPDATE_TIMEADJUST_REQUEST: 'EMPLOYES_UPDATE_TIMEADJUST_REQUEST',
  UPDATE_TIMEADJUST_SUCCESS: 'EMPLOYES_UPDATE_TIMEADJUST_SUCCESS',
  UPDATE_TIMEADJUST_FAILURE: 'EMPLOYES_UPDATE_TIMEADJUST_FAILURE',

  DELETE_TIMEADJUST_REQUEST: 'EMPLOYES_DELETE_TIMEADJUST_REQUEST',
  DELETE_TIMEADJUST_SUCCESS: 'EMPLOYES_DELETE_TIMEADJUST_SUCCESS',
  DELETE_TIMEADJUST_FAILURE: 'EMPLOYES_DELETE_TIMEADJUST_FAILURE'
};