export const peripheralActionTypes = {

  PRINT_TEST: 'PERIPHERAL_PRINT_TEST',
  PRINT_TICKET: 'PERIPHERAL_PRINT_TICKET',
  PRINT_PERIODE_X: 'PERIPHERAL_PRINT_PERIODE_X',
  PRINT_PERIODE_Z: 'PERIPHERAL_PRINT_PERIODE_Z',
  OPEN_DRAWER: 'PERIPHERAL_OPEN_DRAWER',
  OPEN_DRAWER_FAILURE: 'PERIPHERAL_OPEN_DRAWER_FAILURE',
  CLOSE_DRAWER: 'PERIPHERAL_CLOSE_DRAWER'

};