export const signatureActionTypes = {

  CREATE_SIGNATURE_TICKET: 'SIGNATURE_CREATE_SIGNATURE_TICKET',
  CREATE_SIGNATURE_DUPLICATA: 'SIGNATURE_CREATE_SIGNATURE_DUPLICATA',
  CREATE_SIGNATURE_GRANDTOTAL: 'SIGNATURE_CREATE_SIGNATURE_GRANDTOTAL',
  CREATE_SIGNATURE_ARCHIVEFISCALE: 'SIGNATURE_CREATE_SIGNATURE_ARCHIVEFISCALE'

}