export const signatureActionTypes = {

  GET_ALL: 'SIGNATURE_GET_ALL',
  GET_ALL_FAILURE: 'SIGNATURE_GET_ALL_FAILURE',

  STORE_KEYS_REQUEST: 'SIGNATURE_STORE_KEYS_REQUEST',
  STORE_KEYS_SUCCESS: 'SIGNATURE_STORE_KEYS_SUCCESS',
  STORE_KEYS_FAILURE: 'SIGNATURE_STORE_KEYS_FAILURE',

  CREATE_SIGNATURE_TICKET: 'SIGNATURE_CREATE_SIGNATURE_TICKET',
  CREATE_SIGNATURE_DUPLICATA: 'SIGNATURE_CREATE_SIGNATURE_DUPLICATA',
  CREATE_SIGNATURE_GRANDTOTAL: 'SIGNATURE_CREATE_SIGNATURE_GRANDTOTAL',
  CREATE_SIGNATURE_ARCHIVEFISCALE: 'SIGNATURE_CREATE_SIGNATURE_ARCHIVEFISCALE',
  CREATE_SIGNATURE_PISTEDAUDIT: 'SIGNATURE_CREATE_SIGNATURE_PISTEDAUDIT',
  CREATE_SIGNATURE_JET: 'SIGNATURE_CREATE_SIGNATURE_JET',

  UPDATE_NUMEROTATION: 'SIGNATURE_UPDATE_NUMEROTATION',
  STORE_NUMEROTATION: 'SIGNATURE_SET_NUMEROTATION',

}