export const clotureActionTypes = {

  GET_CURRENT_PERIODE: 'CLOTURE_GET_CURRENT_PERIODE',
  GET_TODAY_CA: 'GET_TODAY_CA',

  MAKE_CLOTURE: 'CLOTURE_MAKE_CLOTURE',

  PREVIOUS_PERIOD_ERROR: 'CLOTURE_PREVIOUS_PERIOD_ERROR',

  GET_CLOTURES_LIST_REQUEST: 'CLOTURE_GET_CLOTURES_LIST_REQUEST',
  GET_CLOTURES_LIST_SUCCESS: 'CLOTURE_GET_CLOTURES_LIST_SUCCESS',
  GET_CLOTURES_LIST_FAILURE: 'CLOTURE_GET_CLOTURES_LIST_FAILURE',

  SETSYNCED_REQUEST: 'CLOTURE_SETSYNCED_REQUEST',
  SETSYNCED_SUCCESS: 'CLOTURE_SETSYNCED_SUCCESS',
  SETSYNCED_FAILURE: 'CLOTURE_SETSYNCED_FAILURE'
};