export const clotureActionTypes = {

  GET_CURRENT_PERIODE: 'CLOTURE_GET_CURRENT_PERIODE',

  MAKE_CLOTURE: 'CLOTURE_MAKE_CLOTURE',

  PREVIOUS_PERIOD_ERROR: 'CLOTURE_PREVIOUS_PERIOD_ERROR',

  GET_CLOTURES_LIST_REQUEST: 'CLOTURE_GET_CLOTURES_LIST_REQUEST',
  GET_CLOTURES_LIST_SUCCESS: 'CLOTURE_GET_CLOTURES_LIST_SUCCESS',
  GET_CLOTURES_LIST_FAILURE: 'CLOTURE_GET_CLOTURES_LIST_FAILURE'
};