export const clotureActionTypes = {

  GET_CURRENT_PERIODE: 'CLOTURE_GET_CURRENT_PERIODE',
  GET_TODAY_CA: 'GET_TODAY_CA',

  MAKE_CLOTURE: 'CLOTURE_MAKE_CLOTURE',

  PREVIOUS_PERIOD_ERROR: 'CLOTURE_PREVIOUS_PERIOD_ERROR',

  GET_CLOTURES_LIST_REQUEST: 'CLOTURE_GET_CLOTURES_LIST_REQUEST',
  GET_CLOTURES_LIST_SUCCESS: 'CLOTURE_GET_CLOTURES_LIST_SUCCESS',
  GET_CLOTURES_LIST_FAILURE: 'CLOTURE_GET_CLOTURES_LIST_FAILURE',

  SETSYNCED_REQUEST: 'CLOTURE_SETSYNCED_REQUEST',
  SETSYNCED_SUCCESS: 'CLOTURE_SETSYNCED_SUCCESS',
  SETSYNCED_FAILURE: 'CLOTURE_SETSYNCED_FAILURE',

  PERSIST_FROM_SYNC_REQUEST: 'CLOTURE_PERSIST_FROM_SYNC_REQUEST',
  PERSIST_FROM_SYNC_SUCCESS: 'CLOTURE_PERSIST_FROM_SYNC_SUCCESS',
  PERSIST_FROM_SYNC_FAILURE: 'CLOTURE_PERSIST_FROM_SYNC_FAILURE',

  GET_GTP_REQUEST: 'CLOTURE_GET_GTP_REQUEST',
  GET_GTP_SUCCESS: 'CLOTURE_GET_GTP_SUCCESS',
  GET_GTP_FAILURE: 'CLOTURE_GET_GTP_FAILURE',
  
  UPDATE_GTP_REQUEST: 'CLOTURE_UPDATE_GTP_REQUEST',
  UPDATE_GTP_SUCCESS: 'CLOTURE_UPDATE_GTP_SUCCESS',
  UPDATE_GTP_FAILURE: 'CLOTURE_UPDATE_GTP_FAILURE',

  PERSIST_GTTICKET_REQUEST: 'PERSIST_UPDATE_GTTICKET_REQUEST',
  PERSIST_GTTICKET_SUCCESS: 'PERSIST_UPDATE_GTTICKET_SUCCESS',
  PERSIST_GTTICKET_FAILURE: 'PERSIST_UPDATE_GTTICKET_FAILURE',

  PERSIST_GTPERIODIQUE_REQUEST: 'PERSIST_UPDATE_GTPERIODIQUE_REQUEST',
  PERSIST_GTPERIODIQUE_SUCCESS: 'PERSIST_UPDATE_GTPERIODIQUE_SUCCESS',
  PERSIST_GTPERIODIQUE_FAILURE: 'PERSIST_UPDATE_GTPERIODIQUE_FAILURE',
};