export const parametresActionTypes = {
  GETALL_REQUEST: 'PARAMETRES_GETALL_REQUEST',
  GETALL_SUCCESS: 'PARAMETRES_GETALL_SUCCESS',
  GETALL_FAILURE: 'PARAMETRES_GETALL_FAILURE',

  UPDATE_REQUEST: 'PARAMETRES_UPDATE_REQUEST',
  UPDATE_SUCCESS: 'PARAMETRES_UPDATE_SUCCESS',
  UPDATE_FAILURE: 'PARAMETRES_UPDATE_FAILURE'
};