export const parametresActionTypes = {
  GETALL_REQUEST: 'PARAMETRES_GETALL_REQUEST',
  GETALL_SUCCESS: 'PARAMETRES_GETALL_SUCCESS',
  GETALL_FAILURE: 'PARAMETRES_GETALL_FAILURE',

  UPDATE_REQUEST: 'PARAMETRES_UPDATE_REQUEST',
  UPDATE_SUCCESS: 'PARAMETRES_UPDATE_SUCCESS',
  UPDATE_FAILURE: 'PARAMETRES_UPDATE_FAILURE',

  REPLACE_DATABASE_REQUEST: 'PARAMETRES_REPLACE_DATABASE_REQUEST',
  REPLACE_DATABASE_SUCCESS: 'PARAMETRES_REPLACE_DATABASE_SUCCESS',
  REPLACE_DATABASE_FAILURE: 'PARAMETRES_REPLACE_DATABASE_FAILURE',
  INSTALL_DATABASE: 'PARAMETRES_INSTALL_DATABASE',

  INSTALL_STATION_SUCCESS: 'INSTALL_STATION_SUCCESS',
  INSTALL_STATION_FAILURE: 'INSTALL_STATION_FAILURE'
};