export const notificationActionTypes = {
  INIT_SSE: 'NOTIFICATION_INIT_SSE',
  INIT_SSE_FAILURE: 'NOTIFICATION_INIT_SSE_FAILURE',
  GET_TOKEN: 'NOTIFICATION_GET_TOKEN',
  GET_TOKEN_SUCCESS: 'NOTIFICATION_GET_TOKEN_SUCCESS',
  GET_NOTIFICATION: 'NOTIFICATION_GET_NOTIFICATION'
};