export const notificationActionTypes = {
  INIT_SSE: 'NOTIFICATION_INIT_SSE',
  INIT_SSE_FAILURE: 'NOTIFICATION_INIT_SSE_FAILURE',
  GET_ORDER: 'NOTIFICATION_GET_ORDER',
  ACCEPT_ORDER: 'NOTIFICATION_ACCEPT_ORDER',
  DENY_ORDER: 'NOTIFICATION_DENY_ORDER',
  ORDER_ERROR: 'NOTIFICATION_ORDER_ERROR',
  GET_TOKEN: 'NOTIFICATION_GET_TOKEN',
  GET_TOKEN_SUCCESS: 'NOTIFICATION_GET_TOKEN_SUCCESS',
  GET_NOTIFICATION: 'NOTIFICATION_GET_NOTIFICATION',
  SET_POS: 'NOTIFICATION_SET_POS'
};