export const tableActionTypes = {
  GET_ALL_REQUEST: 'TABLE_GET_ALL_REQUEST',
  GET_ALL_SUCCESS: 'TABLE_GET_ALL_SUCCESS',
  GET_ALL_FAILURE: 'TABLE_GET_ALL_FAILURE',

  ADD_TABLE_REQUEST: 'TABLE_ADD_TABLE_REQUEST',
  ADD_TABLE_SUCCESS: 'TABLE_ADD_TABLE_SUCCESS',
  ADD_TABLE_FAILURE: 'TABLE_ADD_TABLE_FAILURE',

  REMOVE_TABLE_REQUEST: 'TABLE_REMOVE_TABLE_REQUEST',
  REMOVE_TABLE_SUCCESS: 'TABLE_REMOVE_TABLE_SUCCESS',
  REMOVE_TABLE_FAILURE: 'TABLE_REMOVE_TABLE_FAILURE',
  
  TAKE_TABLE: 'TABLE_TAKE_TABLE',
  FREE_TABLE: 'TABLE_FREE_TABLE',

  UPDATE_TABLE_REQUEST: 'TABLE_UPDATE_TABLE_REQUEST',
  UPDATE_TABLE_SUCCESS: 'TABLE_UPDATE_TABLE_SUCCESS',
  UPDATE_TABLE_FAILURE: 'TABLE_UPDATE_TABLE_FAILURE',

  ADD_SALLE_REQUEST: 'ADD_SALLE_TABLE_REQUEST',
  ADD_SALLE_SUCCESS: 'ADD_SALLE_TABLE_SUCCESS',
  ADD_SALLE_FAILURE: 'ADD_SALLE_TABLE_FAILURE',

  REMOVE_SALLE_REQUEST: 'REMOVE_SALLE_TABLE_REQUEST',
  REMOVE_SALLE_SUCCESS: 'REMOVE_SALLE_TABLE_SUCCESS',
  REMOVE_SALLE_FAILURE: 'REMOVE_SALLE_TABLE_FAILURE',

  UPDATE_SALLE_REQUEST: 'TABLE_UPDATE_SALLE_REQUEST',
  UPDATE_SALLE_SUCCESS: 'TABLE_UPDATE_SALLE_SUCCESS',
  UPDATE_SALLE_FAILURE: 'TABLE_UPDATE_SALLE_FAILURE'

};